#GET http://localhost:8080/api/employees/all


POST http://localhost:8080/api/employees/add
Content-Type: application/json

{
  "id": 11,
  "firstName": "Nada",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "phoneNumber": "123-456-7890",
  "hireDate": "2023-01-01",
  "jobTitle": "Software Engineer",
  "managerName": "Jane Smith",
  "salaryAmount": 60000,
  "commissionPct": 0.05,
  "departmentName": "IT",
  "managedDepartmentName": "QA"
}